import Snackbars from "@/components/snackbars/snackbars-container.component";
import type { Metadata } from "next";
import "./globals.css";
import Providers from "./providers";

export const metadata: Metadata = {
  title: "Bufet PW",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico", // /public path
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Providers>
          {children}
          <Snackbars />
        </Providers>
      </body>
    </html>
  );
}
